name: Deploy Delete URL Lambda
on:
  workflow_call:
    inputs:
      lambda_name:
        required: false
        type: string
  push:
    branches:
    - main
    paths:
    - apps/delete-url/**/*
    - .github/workflows/deploy-delete-url-lambda.yaml

defaults:
  run:
    working-directory: apps/delete-url/

permissions:
  id-token: write
  contents: read

jobs:
  deploy_lambda:
    environment: 'staging'
    name: 'Deploy Delete URL Lambda'
    runs-on: ubuntu-latest
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}
        role-to-assume: ${{ secrets.ARN_ROLE_ASUME }}

    - name: Install packages
      run: npm install

    - name: Build
      run: npm run build

    - name: Zip build
      run: cd build && zip -r ../main.zip .

    - name: Update Lambda code
      run: aws lambda update-function-code --function-name=${{ inputs.lambda_name || 'delete-url' }} --zip-file=fileb://main.zip
