name: Deploy Create Short URL Lambda
on:
  workflow_call:
  push:
    branches:
    - main
    paths:
    - apps/create-short-url/**/*
    - .github/workflows/deploy-create-short-url-lambda.yaml

defaults:
  run:
    working-directory: apps/create-short-url/

permissions:
  id-token: write
  contents: read

jobs:
  deploy_lambda:
    name: 'Deploy Create Short URL Lambda'
    runs-on: ubuntu-latest
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: ${{ secrets.AWS_REGION || 'us-east-1' }}
        role-to-assume: ${{ secrets.ARN_ROLE_ASUME }}

    - name: Install packages
      run: npm install

    - name: Build
      run: npm run build

    - name: Zip build
      run: cd build && zip -r ../main.zip .

    - name: Update Lambda code
      run: aws lambda update-function-code --function-name=create-short-url --zip-file=fileb://main.zip
