name: Deploy Infrastructure
on:
  workflow_run:
    workflows:
    - Clean deployment enviroment with Infrastructure
    types:
    - completed
  push:
    branches:
    - main
    paths:
    - iac/**/*
    - .github/workflows/staging.yaml
    - .github/workflows/development.yaml
    - .github/workflows/clean.yaml

permissions:
  id-token: write
  contents: write

jobs:
  terraform:
    environment: 'staging'
    name: 'Terraform'
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.pull_request.merged == true }}
    defaults:
      run:
        working-directory: iac/
    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS Credentials Action For GitHub Actions
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: ${{ secrets.ARN_ROLE_ASUME }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      id: init
      run: terraform init -reconfigure -backend-config="bucket=${{ secrets.BUCKET_NAME }}" -backend-config="key=${{ secrets.KEY_STATE_NAME }}"

    - name: Terraform Format
      id: fmt
      run: terraform fmt

    - name: Auto Commit Changes
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: "Terraform fmt"
        file_pattern: "*.tf"
        commit_user_name: "github-actions[bot]"

    - name: Terraform Plan
      id: plan
      env:
        TF_VAR_lambda_prefix_name: 'staging'
        TF_VAR_env_prefix: 'staging'
      run: |
        terraform plan -out=plan -input=false

    - name: Terraform Apply
      env:
        TF_VAR_lambda_prefix_name: 'staging'
        TF_VAR_env_prefix: 'staging'
      run: terraform apply -auto-approve -input=false plan

  get_changes:
    needs:
    - terraform
    uses: ./.github/workflows/changed-files.yaml
    secrets: inherit
    with:
      working_directory: apps
      # environment: development

  deploy_lambda:
    needs:
    - terraform
    - get_changes
    strategy:
      matrix: ${{ fromJSON(needs.get_changes.outputs.paths_without_prefix) }}
    uses: ./.github/workflows/deploy-lambda.yaml
    secrets: inherit
    with:
      lambda_name: ${{ matrix.paths_without_prefix }}-staging
      working_directory: apps/${{ matrix.paths_without_prefix }}/

